import canonicalLaneMathlib.AdmissibleClass
import DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean.StatisticalManifoldBase
import DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean.FisherInformationMetric
import DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean.AmariChentsovConnections
import DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean.StatisticalCurvatureInvariants
import DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean.DivergenceGeometry

namespace HautevilleHouse
namespace DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean

def ConstrainedDifferentialGeometricStatisticalManifoldsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_differential_geometric_statistical_manifolds_endgame (A : AdmissibleClass) :
    ConstrainedDifferentialGeometricStatisticalManifoldsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DifferentialGeometricAspectsStatisticalManifoldsLemmaCanonicalLaneLean
end HautevilleHouse
